baseURL = "https://thomastanck.github.io/"
languageCode = "en-US"
title = "TT"
copyright = "Copyright (c) 2017, all rights reserved."
theme = "hugo-dusk"

preserveTaxonomyNames = "true"
publishDir = "thomastanck.github.io"

[author]
  name = "Thomas Tan"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Log"
  weight = -130
  identifier = "log"
  url = "/log/"

[[menu.main]]
  name = "Articles"
  weight = -120
  identifier = "article"
  url = "/article/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -100
  identifier = "about"
  url = "/about/"
